// Generated by CoffeeScript 1.7.1
(function() {
  var args, command, greet;

  greet = require('../index');

  args = require('minimist')(process.argv.splice(2));

  command = function() {
    return console.log(greet(args._, args.drunk));
  };

  module.exports = command;

}).call(this);
